In [1]:
import os 

os.chdir("../../")

In [2]:
!pwd

/home/vanishhhed/Desktop/codics/PythonCodics/ML/RAG

In [3]:
from src.dataset.index import FaissIndex


index = FaissIndex()

Created index instance:
  embedding model: Snowflake/snowflake-arctic-embed-m on cpu
  embedding size: 768
  max sequence length: 512
Found and loaded:
  index: indexes/index_FlatIP.ivf
  metadata: indexes/faiss_metadata.pkl
__________________________________________________

In [ ]:
results = index.search("", 15)

for res in results:
    print(res)

{'row_idx': 0, 'title': '0 & 1', 'film_score': 0.3594653606414795, 'plot_text': 'A girl called Zero stands in a crowded street, her occupation an assassin. As she completes her tasks one after another, Zero has been feeling uneasy lately. As her code name suggests, she has nothing to prove her existence. She overlaps herself with the vanishing landscape and begins to wander in search of the meaning of her own existence. At the same time, a young man named One is also wandering the streets, and like Zero, he is an assassin. Surrounded by a sense of emptiness, he is unable to find the value of his own existence. One day, the two of them meet as if they were led together. They sense each other, and by touching each other, they regain their existence and humanity. However, the organization feels that contact between assassins is dangerous, and decides to dispose of them. They call in a highly skilled assassin. Their battle for their own existence begins now!', 'meta_text': 'Released in 2002-02-14 | Rating: 0.0/10 | 0 votes | Popularity: 1.4 | Runtime: 74 min | Genres: Drama, Crime | Directors: Kei Nakata | Cast: Eri Ishikawa, Takayuki Katô, Joe Yamanaka, Isao Natsuyagi, Natsuyo Kanahama | Production countries: Japan | Production companies: Unknown'}
{'row_idx': 767716, 'title': 'Young Maid', 'film_score': 0.3427273631095886, 'plot_text': "Seung-jae, a house owner in his 30s, lives with his nephew Joon-hyeok, but has a hard time doing the chores and so hires a maid. Se-kyeong is an innocent girl who doesn't know much about sex, but she's good with the house work. The two men are excited to have Se-kyeong around and she's happy they are. To Seung-jae, Se-kyeong looks young and innocent, while she appeals as a woman to Joon-hyeok. Seung-jae uses her innocence to teach her things and Joon-hyeok finally makes a video to tell her how her feels about her.  Who will Se-kyeong choose?", 'meta_text': 'Released in 2019-09-19 | Rating: 0.0/10 | 0 votes | Popularity: 2.4 | Runtime: 80 min | Genres: Romance | Directors: No Hyun-jin | Cast: Seo Bo-ra, Min Do-yoon, Shin Joon-hyun | Production countries: South Korea | Production companies: Unknown'}
{'row_idx': 618351, 'title': 'Sierra', 'film_score': 0.3384535610675812, 'plot_text': 'Ring Hassard and his father Jeff, wild horse breakers, live in a hidden mountain eyrie as Jeff is wanted for a murder he didn\'t commit. Things change when they take in a lost young lady, Riley Martin, who finds that Ring has "never seen a woman close up." Jeff is injured, Ring runs afoul of horse thieves and the law, and Riley (who is a lawyer) labors to clear the Hassards (who others would prefer dead).', 'meta_text': 'Released in 1950-05-26 | Rating: 5.4/10 | 13 votes | Popularity: 3.7 | Runtime: 83 min | Genres: Western | Directors: Unknown | Cast: Unknown | Production countries: United States of America | Production companies: Universal International Pictures'}
{'row_idx': 310877, 'title': 'Hypocrisy - Open Air Live at Wacken 2022', 'film_score': 0.3377743363380432, 'plot_text': 'Open Air Live at Wacken 2022 Germany', 'meta_text': 'Released | Rating: 0.0/10 | 0 votes | Popularity: 0.6 | Runtime: 58 min | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production countries: Unknown | Production companies: Unknown'}
{'row_idx': 506505, 'title': 'Onder de huid', 'film_score': 0.3349106013774872, 'plot_text': "A love tattoo is done in no time, but what do you do with the tattoo when the love is over? Frans Bromet goes in search of the stories behind the tattoo during Valentine's week.", 'meta_text': 'Released in 2013-02-11 | Rating: 0.0/10 | 0 votes | Popularity: 0.6 | Runtime: 50 min | Genres: Documentary, TV Movie | Directors: Frans Bromet | Cast: Unknown | Production countries: Netherlands | Production companies: Unknown'}
{'row_idx': 29380, 'title': 'Alter Bridge - Live at the Royal Albert Hall (featuring The Parallax Orchestra)', 'film_score': 0.3314456045627594, 'plot_text': 'Some nights are just pure magic!  In October of 2017, hard rock titans Alter Bridge took to the stage of the iconic Royal Albert Hall in London for two very special headline shows.  Myles Kennedy, Mark Tremonti, Brian Marshall and Scott Phillips treated the capacity crowds to selections from their entire musical catalog.  The set list included some of the band’s biggest hits; rarities and even a few songs the band had never previously performed live.  Adding another career first for the band, Alter Bridge was joined on stage by conductor Simon Dobson and the 52-piece Parallax Orchestra.  Together, everyone on stage during those two extraordinary nights treated the combined crowd of over 10,000 fans to an unforgettable music experience.  Now those two performances have been combined in to one full length, epic concert that is to be shared with fans around the globe in  Alter Bridge: Live At The Royal Albert Hall.', 'meta_text': 'Released in 2018-09-07 | Rating: 9.8/10 | 4 votes | Popularity: 1.7 | Runtime: 166 min | Genres: Music | Directors: Dan Sturgess | Cast: Myles Kennedy, Mark Tremonti, Scott Phillips, Brian Marshall, Simon Dobson | Production countries: Unknown | Production companies: Unknown | Tags: concert, orchestra, heavy metal, live, rock band'}
{'row_idx': 53030, 'title': 'Avanti!', 'film_score': 0.3312618136405945, 'plot_text': "A successful businessman goes to Italy to arrange for the return of his tycoon-father's body only to discover dad died with his mistress of long standing.", 'meta_text': 'Released in 1972-12-17 | Rating: 7.0/10 | 201 votes | Popularity: 10.8 | Runtime: 144 min | Genres: Comedy, Romance | Directors: Billy Wilder | Cast: Jack Lemmon, Juliet Mills, Clive Revill, Edward Andrews, Gianfranco Barra | Production countries: Italy, United States of America | Production companies: The Mirisch Company, United Artists, Jalem Productions, Phalanx Productions, PEA | Tags: island, loss of loved one, italy, based on play or musical'}
{'row_idx': 456923, 'title': 'Moontrap', 'film_score': 0.3258141279220581, 'plot_text': 'The Space Shuttle returns to earth, but some of the equipment brought back on it begins to behave strangely. Scientists are unsure what is happening, and decide to take all necessary precautions.', 'meta_text': 'Released in 1989-04-28 | Rating: 4.7/10 | 86 votes | Popularity: 6.4 | Runtime: 92 min | Genres: Horror, Science Fiction | Directors: Robert Dyke | Cast: Walter Koenig, Bruce Campbell, Robert Kurcz, Leigh Lombardi, Tom Case | Production countries: United States of America | Production companies: Magic Films, Shapiro-Glickenhaus Entertainment'}
{'row_idx': 494647, 'title': 'Not Tonight, Darling', 'film_score': 0.3245398998260498, 'plot_text': "A lonely 'Stay-at-Home' Housewife is being watched every night through the bathroom window by a 'Peeping Tom', who is being put up to it by his friend. She eventually finds out and gets her revenge on them.", 'meta_text': 'Released in 1971-09-23 | Rating: 5.8/10 | 5 votes | Popularity: 1.9 | Runtime: 90 min | Genres: Drama | Directors: Anthony Sloman | Cast: Luan Peters, June Palmer, Thunderclap Newman, Fiona Richmond, Samantha Bond | Production countries: Unknown | Production companies: Mintdene Ltd. Film Productions | Tags: husband wife relationship, peeping tom, voyeurism, bored housewife'}
{'row_idx': 749241, 'title': 'Why Does The River Roar?', 'film_score': 0.3229423463344574, 'plot_text': "Atanes Ghambaryan, resident of Armenian border village, after the captivity during the World War II, turns up abroad in Turkey and dreams of returning to his homeland. During one of night patrols, border guard Armen who is in love with Ghambaryan's daughter Seda, recognizes him on the other side of the river Araks.", 'meta_text': 'Released in 1959-10-05 | Rating: 6.5/10 | 2 votes | Popularity: 0.7 | Runtime: 90 min | Genres: Drama, War | Directors: Grigori Melik-Avakyan | Cast: Hrachia Nersisyan, Avet Avetisyan, Frunze Dovlatyan, Frunzik Mkrtchyan, Davit Malyan | Production countries: Soviet Union | Production companies: Armenfilm'}
{'row_idx': 767710, 'title': 'Young Lovers on Flying Wheels', 'film_score': 0.3194931745529175, 'plot_text': 'Forced to choose between the woman he loves and the dangerous, fast-paced life of motorcycles, what will our hero do? Will he toss the bike aside and pick the girl? Or will he leave the girl in favor of the bike? Or is there a chance for some sort of compromise?', 'meta_text': "Released in 1974-09-20 | Rating: 5.0/10 | 1 votes | Popularity: 1.5 | Runtime: 98 min | Genres: Action | Directors: Ti Lung | Cast: Ti Lung, Rainbow Ching, Helen Ko Ti-Hua, Chiang Nan, Dean Shek Tin | Production countries: Hong Kong | Production companies: Shaw Brothers, Chang's Film Company"}
{'row_idx': 767718, 'title': 'The Young Man', 'film_score': 0.3193187713623047, 'plot_text': 'A young male model twists and manipulates people around him in his unending quest for money and pleasure. He is convinced that he is untouchable and can bend anyone to his will, so not even murder is an obstacle to his ambitions.', 'meta_text': 'Released in 1994-12-17 | Rating: 5.0/10 | 1 votes | Popularity: 1.9 | Runtime: 116 min | Genres: Drama | Directors: Bae Chang-ho | Cast: Lee Jung-jae, Shin Eun-kyung, Lee Eung-kyung, Kim Bo-yeon, Jeon Mi-seon | Production countries: South Korea | Production companies: Bae Chang-ho Production'}
{'row_idx': 767731, 'title': 'Young Masters: Shibi', 'film_score': 0.31509825587272644, 'plot_text': "Young Masters is an original series commissioned by NOWNESS China focusing on traditional Chinese cultures, and how they continue to be defined by a new generation of the country's youth.  High above the clouds in a village in Mao County in Sichuan Prefecture, a post-90’s generation of young cultural guardians work to uphold the values and traditions of ancient Qiang culture. These cultural guardians, known as a ‘Shibi’, remain especially vital for a culture whose knowledge and language exist merely through practice and in sound, and without script. The role of a Shibi involves that of a priest, alongside folk rap, singing, and dance performances, amongst others. As a result, Qiang people have endowed them with a sacred status, believing that they possess a psychic power.", 'meta_text': 'Released in 2021-01-21 | Rating: 0.0/10 | 0 votes | Popularity: 0.0 | Runtime: 5 min | Genres: Documentary | Directors: Unknown | Cast: Unknown | Production countries: China | Production companies: Nowness | Tags: china, tradition, chinese, folk, sichuan, ethnic minority, youth, qiang'}
{'row_idx': 635624, 'title': 'Soul Sessions & Epic Impressions', 'film_score': 0.3141995370388031, 'plot_text': 'Soul Sessions & Epic Impressions features a solid group of early nineties rippers chasing powder. Powder Magazine said. “an infectious, exuberant film that speaks to true skier”, while Ski Magazine called Soul Sessions, “the most hip, exciting, energy packed ski film we’ve seen in a long, long time.”', 'meta_text': 'Released in 1993-01-01 | Rating: 0.0/10 | 0 votes | Popularity: 0.6 | Runtime: Unknown | Genres: Unknown | Directors: Unknown | Cast: Unknown | Production countries: Unknown | Production companies: Matchstick Productions'}
{'row_idx': 537302, 'title': 'The Plague', 'film_score': 0.3115946352481842, 'plot_text': 'A nurse in the Red Crescent (the Turkish equivalent of the Red Cross) fights to save the populace during a plague.', 'meta_text': 'Released in 1954-01-01 | Rating: 0.0/10 | 0 votes | Popularity: 0.6 | Runtime: 67 min | Genres: Drama | Directors: Unknown | Cast: Unknown | Production countries: Turkey | Production companies: Ipar International | Tags: nurse, doctor, epidemic, plague'}

In [5]:
import pandas as pd

df = pd.read_csv("../../data/prep/film_data.csv")

In [6]:
df

,Unnamed: 0,title,release_info,overview,vote_average,vote_count,popularity,runtime,genres,directors,cast,production_countries,production_companies,keywords,title_plot,title_meta
0,0,0 & 1,2002-02-14,"A girl called Zero stands in a crowded street,...",0.0,0.0,1.4000,74.0,"['Drama', 'Crime']",['Kei Nakata'],"['Eri Ishikawa', 'Takayuki Katô', 'Joe Yamanak...",Japan,NaN,NaN,Title: 0 & 1 Plot: A girl called Zero stands i...,0 & 1 | Released in 2002-02-14 | Rating: 0.0/1...
1,1,0 and 26,2016-12-23,The Tampa Bay Buccaneers losing their first ev...,8.5,2.0,0.6000,43.0,['Documentary'],NaN,"['Ron Wolf', 'Steve Spurrier', 'J.K. McKay', '...",NaN,NFL Films,NaN,Title: 0 and 26 Plot: The Tampa Bay Buccaneers...,0 and 26 | Released in 2016-12-23 | Rating: 8....
2,2,0% Down,2008-01-01,Meckseper's parodic high-octane video 0% Down ...,0.0,0.0,0.6000,6.0,NaN,['Josephine Meckseper'],NaN,NaN,NaN,NaN,Title: 0% Down Plot: Meckseper's parodic high-...,0% Down | Released in 2008-01-01 | Rating: 0.0...
3,3,0 Feet Away,2014-12-15,"Looking for a good time, Chase stays home one ...",0.0,0.0,0.6000,10.0,NaN,NaN,NaN,NaN,NaN,NaN,Title: 0 Feet Away Plot: Looking for a good ti...,0 Feet Away | Released in 2014-12-15 | Rating:...
4,4,0 Lux,Released,A man clearing out his recently deceased fathe...,0.0,0.0,0.0000,7.0,['Horror'],NaN,NaN,NaN,NaN,NaN,Title: 0 Lux Plot: A man clearing out his rece...,0 Lux | Released | Rating: 0.0/10 | 0 votes | ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781871,781871,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮,2023-11-21,"The film is about inspiration, reminding the p...",0.0,0.0,0.0000,36.0,['Documentary'],['Regie Mae Adelantar'],"['Lou Veloso', 'Boyet Magale', 'Sylvia Lichauc...",Philippines,The Archivist,"philippines, manila philippines, cultural iden...",Title: 𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮 Plot: The...,𝗦𝗮𝗻𝘁𝗮 𝗔𝗻𝗮: 𝗧𝗵𝗲 𝗪𝗼𝗺𝗯 𝗼𝗳 𝗠𝗮𝗻𝗶𝗹𝗮 | Released in 20...
781872,781872,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵,2025-09-07,Sadie Finloch disappeared in 1973. What happened?,0.0,0.0,0.0357,0.0,NaN,NaN,NaN,United Kingdom,NaN,NaN,Title: 𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵 Plot...,𝗧𝗵𝗲 𝗗𝗶𝘀𝗮𝗽𝗽𝗲𝗮𝗿𝗮𝗻𝗰𝗲 𝗼𝗳 𝗦𝗮𝗱𝗶𝗲 𝗙𝗶𝗻𝗹𝗼𝗰𝗵 | Released ...
781873,781873,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚,Post Production,"In Taiwan’s struggles for housing justice, it ...",0.0,0.0,0.0071,30.0,['Documentary'],NaN,NaN,NaN,NaN,NaN,Title: 𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚 Plot: In Taiwan...,𝘼 𝙋𝙡𝙖𝙘𝙚 𝙎𝙝𝙚 𝘾𝙖𝙡𝙡𝙚𝙙 𝙃𝙤𝙢𝙚 | Post Production | Ra...
781874,781874,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕[[Does Coinbase do instant ...,Released,Coinbase supports💢【𝟷Σ𝟾𝟾𝟾☞𝟼𝟹𝟺☞𝟸𝟹𝟾𝟷〉 instant wit...,0.0,0.0,0.0286,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Title: 〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕[[Does Coinbase do i...,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕[[Does Coinbase do instant ...
781875,781875,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕⌊How to [⍟reverse] a 𝕮𝖔𝖎𝖓𝖇𝖆...,Released,Reversing a {☃️+𝟷✔️(𝟾𝟾𝟾)⋗(𝟼𝟹𝟺)⁂[𝟸𝟹𝟾𝟷]Coinbase ...,0.0,0.0,0.0214,0.0,NaN,NaN,NaN,NaN,NaN,NaN,Title: 〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕⌊How to [⍟reverse] a...,〔∴𝙲𝙾𝙸𝙽𝙱𝙰𝚂𝙴➥𝚂𝚄𝙿𝙿𝙾𝚁𝚃〕⌊How to [⍟reverse] a 𝕮𝖔𝖎𝖓𝖇𝖆...

In [13]:
df_rated = df[df["vote_average"] > 0]
df_rated = df_rated[df_rated["vote_count"] > 10]
df_rated[["vote_average", "vote_count"]].describe()

       vote_average    vote_count
count  52802.000000  52802.000000
mean       6.172338    257.589694
std        1.033228   1186.593073
min        1.179000     11.000000
25%        5.579000     16.000000
50%        6.272500     30.000000
75%        6.895000     87.000000
max       10.000000  34495.000000